name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  
      
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt -t . || echo "No requirements.txt found"
      
      - name: Package Lambda function
        run: |
          cd backend
          zip -r function.zip lambda_function.py
      
      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name VisitorCounter \
            --zip-file fileb://backend/function.zip